/* Main.ino file generated by New Project wizard
 *
 * Created:   Sun Mar 31 2024
 * Processor: Arduino Uno
 * Compiler:  Arduino AVR (Proteus)
 */


int button_pin = 9;

const int out_pins = 7;
int out_put_pins[out_pins] = {2,3,4,5,6,7,8};

const int rows = 6;
const int cols = 7;

int patterns[rows][cols] = {
  {0, 0, 0, 1, 0, 0, 0},
  {1, 0, 0, 0, 0, 0, 1},
  {1, 0, 0, 1, 0, 0, 1},
  {1, 1, 0, 0, 0, 1, 1},
  {1, 1, 0, 1, 0, 1, 1},
  {1, 1, 1, 0, 1, 1, 1}
};

void setup()
{
   Serial.begin(9600);
   // put your setup code here, to run once:
   pinMode(button_pin,INPUT);
   pinMode(LED_BUILTIN,OUTPUT);
   for(int i = 0; i < out_pins;i++)
   {
      pinMode(out_put_pins[i],OUTPUT);
   }
   randomSeed(analogRead(0));
}

void loop()
 { 
 // put your main code here, to run repeatedly:
   int buttonState = digitalRead(button_pin);
   
   if(buttonState == HIGH){
      int rand = random(1,7);
      setDice(rand);
      delay(100);
   }
   
   
 
 }
 
 
 void setDice(int val){
   for(int i =0; i<cols;i++){
      int state = patterns[val-1][i];
      digitalWrite(out_put_pins[i],state);
   }
 }
